In [1]:
# import required libraries
import pandas as pd
import numpy as np

In [2]:
# Reading the dataset
df = pd.read_csv('/content/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.shape

(108, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [5]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [8]:
df['State'] = le.fit_transform(df.State)

In [9]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [11]:
X =df.iloc[:,:-1].values

In [13]:
y= df.iloc[:,4:5].values

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [15]:
x_train.shape, x_test.shape

((75, 4), (33, 4))

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
# creating ANN skeleton

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))
regressor.add(Dense(12,activation='relu'))
regressor.add(Dense(8,activation='relu'))
regressor.add(Dense(9,activation='relu'))
regressor.add(Dense(1,activation='linear'))


In [18]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss ='mse',metrics=['mse'] )


In [19]:
# training the model
regressor.fit(x_train,y_train,batch_size=10,epochs =300)


Epoch 1/300
8/8 [==============================] - 1s 3ms/step - loss: 16757245952.0000 - mse: 16757245952.0000
Epoch 2/300
8/8 [==============================] - 0s 2ms/step - loss: 15736519680.0000 - mse: 15736519680.0000
Epoch 3/300
8/8 [==============================] - 0s 2ms/step - loss: 15078821888.0000 - mse: 15078821888.0000
Epoch 4/300
8/8 [==============================] - 0s 2ms/step - loss: 14728605696.0000 - mse: 14728605696.0000
Epoch 5/300
8/8 [==============================] - 0s 2ms/step - loss: 14503660544.0000 - mse: 14503660544.0000
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 14290598912.0000 - mse: 14290598912.0000
Epoch 7/300
8/8 [==============================] - 0s 2ms/step - loss: 14103093248.0000 - mse: 14103093248.0000
Epoch 8/300
8/8 [==============================] - 0s 2ms/step - loss: 13896276992.0000 - mse: 13896276992.0000
Epoch 9/300
8/8 [==============================] - 0s 2ms/step - loss: 13655714816.0000 - mse: 136557137

In [20]:
# testing the model

y_pred = regressor.predict(x_test)


2/2 [==============================] - 0s 4ms/step


In [21]:
y_pred

array([[ 44510.285],
       [124406.02 ],
       [ 82486.164],
       [182390.95 ],
       [ 95183.52 ],
       [123917.57 ],
       [131432.33 ],
       [167724.92 ],
       [120504.99 ],
       [ 47624.453],
       [105586.82 ],
       [124267.766],
       [ 44510.285],
       [134869.8  ],
       [ 70511.164],
       [130988.3  ],
       [130988.3  ],
       [103110.45 ],
       [ 76039.305],
       [140564.19 ],
       [148230.61 ],
       [160854.86 ],
       [109857.97 ],
       [166539.8  ],
       [ 94260.414],
       [177943.14 ],
       [132033.39 ],
       [ 18625.977],
       [ 89591.07 ],
       [158430.45 ],
       [ 72505.86 ],
       [209029.61 ],
       [207108.55 ]], dtype=float32)

In [22]:
from sklearn.metrics import r2_score

In [23]:
# evaluating the model with r2 score

r2_score(y_test,y_pred)

0.8875329389793383

In [26]:
y_pred.flatten()

array([ 44510.285, 124406.02 ,  82486.164, 182390.95 ,  95183.52 ,
       123917.57 , 131432.33 , 167724.92 , 120504.99 ,  47624.453,
       105586.82 , 124267.766,  44510.285, 134869.8  ,  70511.164,
       130988.3  , 130988.3  , 103110.45 ,  76039.305, 140564.19 ,
       148230.61 , 160854.86 , 109857.97 , 166539.8  ,  94260.414,
       177943.14 , 132033.39 ,  18625.977,  89591.07 , 158430.45 ,
        72505.86 , 209029.61 , 207108.55 ], dtype=float32)

In [30]:
# Comparing the actual and predicted y values

pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_value':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_value
0        64926.08       44510.285156
1       146121.95      124406.023438
2        90708.19       82486.164062
3       191050.39      182390.953125
4       108552.04       95183.523438
5       144259.40      123917.570312
6       124266.90      131432.328125
7       155752.60      167724.921875
8       126992.93      120504.992188
9        42559.73       47624.453125

In [31]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [32]:
# testing with random values

regressor.predict([[142107.34,91391.77,366168.42,2]])

1/1 [==============================] - 0s 33ms/step


array([[166540.67]], dtype=float32)

In [33]:
regressor.predict([[144107.12,118671.85,12345.42,0]])

1/1 [==============================] - 0s 35ms/step


array([[159516.98]], dtype=float32)